### ISSUE TITLE
cannot compile to go app on M1 arch

### ISSUE THREAD

**Issue by eschmidbauer** [streamer45/silero-vad-go#4]
I am getting the following error:
when trying to build on my local machine
```C_INCLUDE_PATH=/opt/homebrew/Cellar/onnxruntime/1.17.0/include/onnxruntime go build```

```cannot use &hcNodeInputDims[0] (value of type *_Ctype_long) as *_Ctype_longlong value in variable declaration```

![image](https://github.com/streamer45/silero-vad-go/assets/7139998/a9d891e5-a564-4cfa-a8ef-df38b2e5046d)

**Comment by streamer45** [comment]
Hi @eschmidbauer. This is a known issue which we are looking to fix as part of https://github.com/streamer45/silero-vad-go/pull/3. So far the code will compile on Linux only unless you manually update those failing types as they are slightly different on M1 machines.

/cc @cpoile

**Comment by streamer45** [comment]
This should be supported now.
