### ISSUE TITLE
Max speech duration option

### ISSUE THREAD

**Issue by KazBrekker1** [streamer45/silero-vad-go#6]
Hey

I was trying the python version of the silero interface, and there was a "Max speech duration" option with the following description:
- Maximum duration of speech chunks in seconds

For the go version of the silero interface, it is missing.
Do you plan to implement it?

**Comment by streamer45** [comment]
Hi! I think it would be trivial to implement but not really needed for our current use case so it's not in the roadmap if that's what you are asking.

**Comment by KazBrekker1** [comment]
Ok, thank you so much.
